# colorscheme:
# import = ["~/.config/alacritty/catppuccin-frappe.toml"]
import = ["~/.config/alacritty/everforest-dark.toml"]

[env]
TERM = "xterm-256color"

[window]
# startup_mode = "Maximized"
dimensions = { columns = 80, lines = 24 }

[font]
# normal = { family = "CommitMono Nerd Font", style = "Regular" }
normal = { family = "SauceCodePro Nerd Font" }
size = 16
offset = {y = 3}
