# colorscheme:
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
dimensions = { columns = 80, lines = 24 }

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
size = 14
offset = {y = 3}
