# colorscheme:
import = ["~/.config/alacritty/catppuccin-latte.toml"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 88, lines = 27 }

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
size = 14
offset = {y = 3}
